#! /usr/bin/env python3

from math import sqrt
import sys
from matrix import Square_Matrix
from function import *

def print_matrice(matrix):
	j = 0
	x = 0
	while j != matrix.size:
		x = 0
		while x != matrix.size:
			if x != matrix.size - 1:
				print("%.2f" % matrix.matrice[j][x], "	", end = "")
			else:
				print("%.2f" % matrix.matrice[j][x])
			x = x + 1
		j = j + 1

if __name__ == "__main__":
	try:
		a = int(sqrt(len(sys.argv) - 2))
		a == sqrt(len(sys.argv) - 2)
	except:
		print ("Error number argument")
		sys.exit(84)
	matrix = Square_Matrix(a, sys.argv[2:])
	if sys.argv[1] == "COS":
		matrix = cosinus(matrix)
	elif sys.argv[1] == "EXP":
		matrix = exponentielle(matrix)
	elif sys.argv[1] == "SIN":
		matrix = sinus(matrix)
	else:
		print("retry with -h")
	print_matrice(matrix)
