#! /usr/bin/env python3

from math import sqrt
import sys
from matrix import Square_Matrix

def factorielle(nb):
	a = 1
	while nb != 0:
		a = a * nb
		nb = nb - 1
	return (a)

def cosinus(matrix):
	i = 0
	tmp = Square_Matrix(matrix.size, [0] * matrix.size)
	while i != 17:
		tmp = tmp + (pow(-1, i) * (matrix ** (2 * i)) / factorielle(2 * i))
		i = i + 1
	return (tmp)

def print_matrice(matrix):
	j = 0
	x = 0
	while j != matrix.size:
		x = 0
		while x != matrix.size:
			if x != matrix.size - 1:
				print("%.2f" % matrix.matrice[j][x], "	", end = "")
			else:
				print("%.2f" % matrix.matrice[j][x])
			x = x + 1
		j = j + 1

if __name__ == "__main__":
	try:
		a = int(sqrt(len(sys.argv) - 2))
		a == sqrt(len(sys.argv) - 2)
	except:
		print ("Error number argument")
		sys.exit(84)
	matrix = Square_Matrix(a, sys.argv[2:])
	if sys.argv[1] == "COS":
		matrix = cosinus(matrix)
	print_matrice(matrix)
